Areas/Administrator/Controllers/EmployeeAttendanceController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using MySoft.Employee.Entities.Attendance;
using MySoftCorporation.Helpers;
using MySoftCorporation.Services.Services;

namespace MySoftCorporation.Areas.Administrator.Controllers
{
    [Authorize]
    public class EmployeeAttendanceController : Controller
    {
        private EmployeeAttendanceService _employeeAttendanceService;

        public EmployeeAttendanceController()
        {
            _employeeAttendanceService = new EmployeeAttendanceService();
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetList()
        {
            string UserID = UserHelperInfo.GetUserId();
            if (!await _employeeAttendanceService.IsEmployee(UserID))
            {
                return HttpNotFound("Employee Not Found In Database Only Employee Can Give Attendance");
            }
            return View("_List", await _employeeAttendanceService.GetEmployeeAttendances());
        }

        [Authorize]
        public async Task<ActionResult> GiveAttendance()
        {
            string UserID = UserHelperInfo.GetUserId();
            var Employee = await _employeeAttendanceService.GetEmployee(UserID);
            if (Employee != null)
            {
                var todayAttendance = await _employeeAttendanceService.GetTodayAttendance(Employee.ID);
                if (todayAttendance == null)
                {
                    EmployeeAttendance employeeAttendance = new EmployeeAttendance()
                    {
                        Agent = UserInfo.Agent(),
                        IP = UserInfo.IP(),
                        Latitude = "N/A",
                        Longitude = "N/A",
                        TakenById = Employee.ID,
                        EmployeeId = Employee.ID
                    };
                    return View("ClockIn", employeeAttendance);
                }
                else
                {
                    return View("ClockOut", todayAttendance);
                }
            }
            else
            {
                return new HttpNotFoundResult();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<JsonResult> ClockIn(EmployeeAttendance model)
        {
            model.Status = "N/A";
            model.ClockIn = DateTimeHelper.Now();
            model.ModifiedDate = DateTimeHelper.Now();
            model.Date = DateTime.Today;
            var (IsTrue, ResponseMSG) = await _employeeAttendanceService.ClockInNow(model);
            JsonResult jsonResult = new JsonResult
            {
                Data = new { IsSuccess = IsTrue, msg = ResponseMSG }
            };
            return jsonResult;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<JsonResult> ClockOut(EmployeeAttendance model)
        {
            model.ClockOut = DateTimeHelper.Now();
            model.ModifiedDate = DateTimeHelper.Now();
            model.Status = "P";
            var (IsTrue, ResponseMSG) = await _employeeAttendanceService.ClockOutNow(model);
            JsonResult jsonResult = new JsonResult
            {
                Data = new { IsSuccess = IsTrue, msg = ResponseMSG }
            };
            return jsonResult;
        }

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Delete(int Id)
        {
            var (IsTrue, Msg) = await _employeeAttendanceService.Delete(Id);
            if (IsTrue)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound(Msg);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_employeeAttendanceService != null)
                {
                    _employeeAttendanceService = null;
                }
            }

            base.Dispose(disposing);
        }
    }
}

Areas/Administrator/Views/EmployeeAttendance/ClockIn.cshtml
@model MySoft.Employee.Entities.Attendance.EmployeeAttendance
@{
    ViewBag.Title = "Clock In";
}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="card-title">Clock In</div>
        </div>
        <div class="card-body">
            <div class="row">
                @using (Html.BeginForm("ClockIn", "EmployeeAttendance", FormMethod.Post, new { @id = "myForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.IP)
                    @Html.HiddenFor(x => x.Agent)
                    @Html.HiddenFor(x => x.Latitude)
                    @Html.HiddenFor(x => x.Longitude)
                    @Html.HiddenFor(x => x.TakenById)
                    @Html.HiddenFor(x => x.EmployeeId)
                }
            </div>     
            <div id="FeedBack">

            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" id="ClockInButton">Clock Me In Now</button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#ClockInButton").click(function (e) {
            var Button = $(this);
            Button.prop("disabled", true);
            $("#FeedBack").html("<div class='alert alert-warning'>Wait ! Make you present in while</div>");
            $.ajax({
                type: "POST",
                url: "@Url.Action("ClockIn")",
                data: $("#myForm").serialize(),
                success: function (response) {
                    if (response.IsSuccess) {
                        window.location.replace("@Url.Action("Index")");
                    }
                    else {
                        Button.prop("disabled", false);
                        $("#FeedBack").html("<div class='alert alert-danger'>"+response.msg+"</div>");
                    }
                }
            });

        });
    });
</script>

Areas/Administrator/Views/EmployeeAttendance/ClockOut.cshtml
@model MySoft.Employee.Entities.Attendance.EmployeeAttendance
@{
    ViewBag.Title = "ClockOut";
}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="card-title">Clock Out or Check Out</div>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("ClockOut", "EmployeeAttendance", FormMethod.Post,new { @id = "myForm" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)
                @Html.HiddenFor(x => x.IP)
                @Html.HiddenFor(x => x.Agent)
                @Html.HiddenFor(x => x.Latitude)
                @Html.HiddenFor(x => x.Longitude)
                @Html.HiddenFor(x => x.TakenById)
                @Html.HiddenFor(x => x.EmployeeId)
                @Html.HiddenFor(x => x.ClockIn)
                @Html.HiddenFor(x => x.Status)
                @Html.HiddenFor(x=>x.Date)
            }
            <div  id="FeedBack">

            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" id="ClockOutButton">Click Here to Clock Out </button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#ClockOutButton").click(function (e) {
            var Button = $(this);
            Button.prop("disabled", true);
            $("#FeedBack").html("<div class='alert alert-warning'>Wait ! Make you leave in while</div>");
            $.ajax({
                type: "POST",
                url: "@Url.Action("ClockOut")",
                data: $("#myForm").serialize(),
                success: function (response) {
                    if (response.IsSuccess) {
                        window.location.replace("@Url.Action("Index")");
                    }
                    else {
                        Button.prop("disabled", false);
                        $("#FeedBack").html("<div class='alert alert-danger'>"+response.msg+"</div>");
                    }
                }
            });

        });
    });
</script>

Areas/Administrator/Views/EmployeeAttendance/Index.cshtml
@{
    ViewBag.Title = "Attendance";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <a href="@Url.Action("GiveAttendance","EmployeeAttendance")" class="btn btn-primary"><i class="fa fa-check mr-1"></i> Take/Give</a>
            </div>
        </div>
        <div class="card-body" id="divResponse">
            <button class="btn btn-primary btn-flat" onclick="GetHistory()">Click here to Load History</button>
        </div>
    </div>
</div>
<script>
    function GetHistory() {
        $.get("@Url.Action("GetList", "EmployeeAttendance")", { name: "value" },
            function (data, textStatus, jqXHR) {
                $("#divResponse").html(data);
            }
        );
    }
</script>

Areas/Administrator/Views/EmployeeAttendance/_List.cshtml
@model IEnumerable<MySoft.Employee.Entities.Attendance.EmployeeAttendance>
@{ 
    Layout = null;
}

<div style="overflow:auto;">
    <table class="table table-custom table-bordered table-hover">
        <tr>
            <th> @Html.DisplayNameFor(model => model.Employee.FirstName)</th>
            <th> @Html.DisplayNameFor(model => model.Employee.LastName)</th>
            <th> @Html.DisplayNameFor(model => model.Date) </th>
            <th> @Html.DisplayNameFor(model => model.ClockIn)</th>
            <th> @Html.DisplayNameFor(model => model.CheckOut) </th>
            <th> @Html.DisplayNameFor(model => model.CheckIn)</th>
            <th> @Html.DisplayNameFor(model => model.ClockOut)</th>
            <th> @Html.DisplayNameFor(model => model.ModifiedDate)</th>
            <th> @Html.DisplayNameFor(model => model.Status) </th>
            <th> @Html.DisplayNameFor(model => model.IP)</th>
            <th> @Html.DisplayNameFor(model => model.Agent) </th>
            <th> @Html.DisplayNameFor(model => model.Latitude) </th>
            @if (User.IsInRole("Administrator"))
            {
            <th> @Html.DisplayNameFor(model => model.Longitude)</th>
            }
            <th> Action</th>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td> @Html.DisplayFor(modelItem => item.Employee.FirstName)</td>
        <td> @Html.DisplayFor(modelItem => item.Employee.LastName) </td>
        <td> @Html.DisplayFor(modelItem => item.Date)</td>
        <td> @Html.DisplayFor(modelItem => item.ClockIn)</td>
        <td> @Html.DisplayFor(modelItem => item.CheckOut) </td>
        <td> @Html.DisplayFor(modelItem => item.CheckIn) </td>
        <td> @Html.DisplayFor(modelItem => item.ClockOut)</td>
        <td> @Html.DisplayFor(modelItem => item.ModifiedDate)</td>
        <td> @Html.DisplayFor(modelItem => item.Status)</td>
        <td> @Html.DisplayFor(modelItem => item.IP)</td>
        <td> @Html.DisplayFor(modelItem => item.Agent)</td>
        <td> @Html.DisplayFor(modelItem => item.Latitude)</td>
        <td> @Html.DisplayFor(modelItem => item.Longitude)</td>
        @if (User.IsInRole("Administrator"))
        {
            <td> @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-block" })</td>
        }

    </tr>
        }
    </table>
</div>