Areas/Administrator/Models/AdmissionViewModel.cs
using MySoft.Institute.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySoftCorporation.Areas.Administrator.Models
{
    public class AdmissionViewModel : Admission
    {
        public IEnumerable<Admission> Admissions { get; set; }
        public string SearchTerm { get; set; }
    }

    public class AdmissionActionModel : Admission
    {
    }
}

Areas/Administrator/Controllers/AdmissionController.cs
using MySoft.Institute.Entities;
using MySoftCorporation.Areas.Administrator.Models;
using MySoftCorporation.Helpers;
using MySoftCorporation.Services;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MySoftCorporation.Areas.Administrator.Controllers
{
    public class AdmissionController : AdminAuthorizeController
    {
        private readonly AdmissionService service;
        public AdmissionController()
        {
            service = new AdmissionService();
        }
       
        public async Task<ActionResult> Index()
        {
            AdmissionViewModel admissionViewModel = new AdmissionViewModel
            {
                Admissions = await service.GetAdmissons()
            };
            return View(admissionViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> ApproveAdmission(AdmissionActionModel admissionActionModel)
        {
            JsonResult jsonResult = new JsonResult();
            var OldAdmission = service.GetByID(admissionActionModel.AdmissionID);
            if (OldAdmission != null)
            {
                Admission admission = new Admission()
                {
                    AdmissionID = OldAdmission.AdmissionID,
                    StudentID = OldAdmission.StudentID,
                    CourseID = OldAdmission.CourseID,
                    IsConfirmed = true,
                    UserID = UserHelperInfo.GetUserId(),
                    ModifiedOn = DateTimeHelper.Now(),
                    IP = UserInfo.IP(),
                    Agent = UserInfo.Agent(),
                    Location = UserInfo.Location()
                };
                var (IsTrue, Msg) = await service.ApproveAdmission(admission);
                jsonResult.Data = new { Success = IsTrue, Message = Msg };
            }
            else
            {
                jsonResult.Data = new { Success = false, Message = "No Admission Found In DB" };
            }

            return jsonResult;
        }
    }
}

Areas/Administrator/Views/Admission/Index.cshtml
@model MySoftCorporation.Areas.Administrator.Models.AdmissionViewModel
@{
    ViewBag.Title = ViewContext.RouteData.Values["controller"].ToString();
}
<div class="col-md-12">
    <div class="card form-group">
        <div class="card-header form-group ">
            <h3 class="card-title">@ViewBag.Title</h3>
        </div>
    </div>

    <div class="card form-group">
        <div class="col-md-12 col-sm-12 col-lg-12" style="
    margin-top: 10px;
">
            <form>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" value="@Model.SearchTerm" name="SearchTerm" placeholder="Search @ViewContext.RouteData.Values["controller"].ToString() Here " required>
                    <span class="input-group-append">
                        <button type="submit" class="btn btn-info btn-sm btn-flat"><i class="fa fa-search mr-1"></i> Search</button>
                        <a class="btn btn-primary btn-sm btn-flat " href="@Url.Action("Index",ViewContext.RouteData.Values["controller"].ToString())"><i class="fa fa-circle mr-1"></i> Reset</a>
                        <button type="button" data-href="@Url.Action("Action",ViewContext.RouteData.Values["controller"].ToString())" class="data-btn btn btn-default" data-toggle="modal" data-target="#actionModal">
                            <i class="fa fa-plus mr-1"></i> Create
                        </button>
                    </span>
                </div>
            </form>
        </div>
        @{Html.RenderPartial("_Listing", Model);}
    </div>

    <!-- /.card-body -->
</div>
<div class="modal fade" id="actionModal" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" id="formModal">

        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.card -->
<div class="modal fade" id="deleteModal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" id="deleteModalContent">
    </div>
</div>
<script>
    $(".data-btn").click(function (e) {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#formModal").html(response);
            });

    });
</script>

Areas/Administrator/Views/Admission/_Listing.cshtml
@model MySoftCorporation.Areas.Administrator.Models.AdmissionViewModel

@if (Model != null && Model.Admissions.Count() > 0)
{
    <!-- /.card-header -->
    <div class="card-body">
        <div style="overflow-x:auto">
            <table class="table-custom table table-bordered table-condenced  table-hover table-striped">
                <thead>
                    <tr>
                        <th style="width: 10px">S#</th>
                        <th>Ad.ID</th>
                        <th>St.ID</th>
                        <th>Student</th>
                        <th>Course</th>
                        <th>IsApproved</th>
                        <th>Date</th>
                        <th>ApprovedBy</th>
                        <th>IP</th>
                        <th>Agent</th>
                        <th>Localtion</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 1;
                    }
                    @foreach (var item in Model.Admissions)
                    {
                        <tr>
                            <td> @i </td>
                            <td>@item.AdmissionID</td>
                            <td>@item.Student.ID</td>
                            <td>@item.Student.FirstName @item.Student.LastName</td>
                            <td>@item.Course.Title</td>
                            @if (item.IsConfirmed)
                            {
                                <th>Approved</th>
                            }
                            else
                            {
                                <td>
                                    <button class="dbtn btn-success btn-block btn-flat" onclick="ApproveAdmission(this,@item.AdmissionID)">
                                        <i class="fa fa-eye-dropper mr-1"></i> Approved Now
                                    </button>
                                </td>
                            }
                            <td>@item.ModifiedOn</td>
                            <td>@item.User.UserName</td>
                            <td>@item.IP</td>
                            <td>@item.Agent</td>
                            <td>@item.Location</td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function ApproveAdmission(element,intAdmissionID) {
            $(element).prop("disabled", true);
            $.ajax({
                type: "POST",
                url: "@Url.Action("ApproveAdmission","Admission")",
                data: { AdmissionID: intAdmissionID}
            })
                .done(function (response) {
                    if (response.Success) {
                        location.reload();
                    }
                    else {
                        $(element).prop("disabled", false);
                        alert(response.Message);
                    }
                });
        }
    </script>
}
else
{
    <div class="col-md-12">
        <div class=" form-group alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-info"></i> Oops!</h5>
            No @ViewContext.RouteData.Values["controller"].ToString() Exist in Database!
        </div>
    </div>

}